version: '3.8'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    networks: []
    container_name: dhcprs-server
    privileged: true
  client:
    build:
      context: client
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]
    container_name: dhcprs-client
    privileged: true
    networks: []
